"""add friendship table

Revision ID: 2e380397f31a
Revises: 9d75d622ab5b
Create Date: 2025-12-29 15:46:45.848430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.types import GUID

# revision identifiers, used by Alembic.
revision: str = "2e380397f31a"
down_revision: Union[str, Sequence[str], None] = "9d75d622ab5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

friendship_enum = sa.Enum(
    "pending",
    "accepted",
    "rejected",
    name="friendshipstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("id", GUID(), nullable=False, primary_key=True),
        sa.Column("requester_id", GUID(), nullable=False),
        sa.Column("receiver_id", GUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(name="friendshipstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friendships")
    # ### end Alembic commands ###
