"""add unread conversation feature

Revision ID: 3dad097a16db
Revises: b643a7d84018
Create Date: 2025-12-20 21:13:27.969497

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3dad097a16db"
down_revision: Union[str, Sequence[str], None] = "b643a7d84018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
