"""add conversation table

Revision ID: 455d320fe88f
Revises: 2e380397f31a
Create Date: 2025-12-29 22:15:39.395144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "455d320fe88f"
down_revision: Union[str, Sequence[str], None] = "2e380397f31a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user1_id", GUID(), nullable=False),
        sa.Column("user2_id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user1_id", "user2_id", name="unique_conversation_pair"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversations")
    # ### end Alembic commands ###
