"""Initial migration

Revision ID: 52b1814a1a5e
Revises:
Create Date: 2025-12-21 00:32:23.459395

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "52b1814a1a5e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
