"""add conversation settings table

Revision ID: 6ecf907ed1a5
Revises: 73ac865bce83
Create Date: 2025-12-29 22:33:59.239959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "6ecf907ed1a5"
down_revision: Union[str, Sequence[str], None] = "73ac865bce83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_settings",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("conversation_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_settings")
    # ### end Alembic commands ###
