"""add conversation unread table

Revision ID: 73ac865bce83
Revises: 22ad49e81652
Create Date: 2025-12-29 22:32:15.415404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "73ac865bce83"
down_revision: Union[str, Sequence[str], None] = "22ad49e81652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_unread",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("conversation_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_unread")
    # ### end Alembic commands ###
